---
- name: add nginx service
  become: yes
  template:
    src: nginx.service.j2
    dest: /lib/systemd/system/nginx.service
    owner: root
    group: root
  notify:
    - restart nginx

- name: reload systemd
  become: yes
  command: systemctl daemon-reload

- name: start nginx service
  become: yes
  service:
    name: nginx
    enabled: yes
    state: started
