---
- include: docker.yml

- name: install docker
  sudo: yes
  apt:
    name: lxc-docker
    state: latest

- name: start docker
  sudo: yes
  service:
    name: docker
    enabled: yes
    state: started

- name: add common services
  sudo: yes
  with_items: common_services
  template:
    src: "{{ item.name }}.service.j2"
    dest: "/lib/systemd/system/{{ item.name }}.service"
    owner: root
    group: root

- name: reload systemd
  sudo: yes
  command: systemctl daemon-reload

- name: start common services
  sudo: yes
  with_items: common_services
  service:
    name: "{{ item.name }}"
    enabled: yes
    state: started

- name: install common packages
  sudo: yes
  with_items: common_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest
