---
- name: clone one love repos
  with_items: vagrant_repos
  git:
    repo: "{{ item.url }}"
    dest: /vagrant/projects/{{ item.name }}
    accept_hostkey: yes
    update: no

- name: put project in path
  sudo: yes
  copy:
    src: project-path.sh
    dest: /etc/profile.d/project-path.sh
    owner: root
    group: root
    mode: 0644

- name: configure backend
  sudo: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app onelove/backend:latest consul-template -once -config /usr/src/app/consul/onelove.conf"

- name: create default admin
  sudo: yes
  command: "docker run -i --rm -v /vagrant/projects/backend:/usr/src/app --link mongodb:mongodb onelove/backend:latest ./create_default_admin.py"

- name: install packages
  sudo: yes
  with_items: vagrant_packages
  apt:
    pkg: "{{ item.name }}"
    state: latest

- name: install requirements
  sudo: yes
  pip:
    requirements: /vagrant/projects/backend/requirements_dev.txt

- name: get npm binary
  get_url:
    url: https://www.npmjs.org/install.sh
    validate_certs: no
    dest: /tmp/npm-install.sh

- name: install npm
  sudo: yes
  command: bash /tmp/npm-install.sh
  args:
    creates: /usr/bin/npm
