---
- name: add unstable repo
  sudo: yes
  template:
    src: stretch.list.j2
    dest: /etc/apt/sources.list.d/stretch.list
    owner: root
    group: root

- name: pin docker.io
  sudo: yes
  template:
    src: docker-preferences.j2
    dest: /etc/apt/preferences.d/docker
    owner: root
    group: root
